#ifndef __PANEL_CONF_H
#define __PANEL_CONF_H

#define PANEL_NAME "SL seq"

#define PANEL_SCALE 2
#define PANEL_UNIT_SIZE 46
#define PANEL_UNIT_GAP 4
#define PAN_BORDER 20

#define DISP_XSIZE 128
#define DISP_YSIZE 64

#define PAN_BUT_INC ((PANEL_UNIT_SIZE + PANEL_UNIT_GAP) * PANEL_SCALE)
#define PAN_ELEMENTS_WIDTH ((PANEL_UNIT_SIZE * 4 + PANEL_UNIT_GAP * 3) * PANEL_SCALE)
// #define PAN_1ST_ROW_INT ((PAN_ELEMENTS_WIDTH - (PANEL_UNIT_SIZE * PANEL_SCALE * 3)) / 4)

#define PANEL_SIZE_X (PAN_BORDER * 2 / PANEL_SCALE + PANEL_UNIT_SIZE * 4 + PANEL_UNIT_GAP * 3)
#define PANEL_SIZE_Y (PAN_BORDER * 2 / PANEL_SCALE + PANEL_UNIT_SIZE * 2 + PANEL_UNIT_GAP * 3 + (DISP_YSIZE + 6) * 3 / 2)

// OLED STYLE
#define DISPM_COLOR_BACK 0x00000000
#define DISPM_COLOR_PIXEL 0x0000FF3F

// #define FORM_COLOR_R 125
// #define FORM_COLOR_G 127
// #define FORM_COLOR_B 108
// #define FORM_COLOR_A 0
// #define FORM_COLOR_LABEL 0xFF000000

// #define BUT_SIZE_Y 46 // must be same as x

#endif // __PANEL_CONF_H