# DIR_HWPANELEMU := libs/hwPanelEmulator
# DIR_OBJ := build

# outputs:
# FLAGS_C_HWPANELEMU_EXPORT := $(shell sdl2-config --cflags)
# OBJECTS_HWPANELEMU - added to OBJECTS_TARGET

# $(info Variables: $(.VARIABLES))

ifeq ($(DIR_HWPANELEMU),)
$(error DIR_HWPANELEMU is not set)
endif
ifeq ($(FLAGS_C_HWPANELEMU_CONFIG),)
$(error FLAGS_C_HWPANELEMU_CONFIG is not set)
endif
ifeq ($(OBJECTS_TARGET),)
$(warning OBJECTS_TARGET is not set)
endif

DIRS_INCLUDE_HWPANELEMU := $(DIR_HWPANELEMU)

SOURCES_C_HWPANELEMU := $(wildcard $(DIR_HWPANELEMU)/*.c)
OBJECTS_HWPANELEMU := $(addprefix $(DIR_OBJ)/, $(SOURCES_C_HWPANELEMU:.c=.o))
OBJECTS_TARGET += $(OBJECTS_HWPANELEMU)
DIR_OBJ_HWPANELEMU := $(DIR_OBJ)/$(DIR_HWPANELEMU)

LIBS_HWPANELEMU := # sdl2 flags are generated by dedicated config
LIBS_HWPANELEMU += portmidi
LIBS_HWPANELEMU += libserialport
LIBS_HWPANELEMU += portaudio-2.0

# FLAGS_C_HWPANELEMU_EXPORT := $(shell sdl2-config --cflags) # !!!!!!!!!!!
FLAGS_C_HWPANELEMU := $(FLAGS_C_COMMON)
FLAGS_C_HWPANELEMU += $(addprefix -I,$(DIRS_INCLUDE_HWPANELEMU))
FLAGS_C_HWPANELEMU += $(shell pkg-config $(LIBS_HWPANELEMU) --cflags)
FLAGS_C_HWPANELEMU += -std=c11
FLAGS_C_HWPANELEMU += -MMD -MP
FLAGS_C_HWPANELEMU += -Wall -Wextra -Wpedantic
FLAGS_C_HWPANELEMU += -Wdouble-promotion
ifeq ($(DEBUG), 1)
FLAGS_C_HWPANELEMU += -DSDL_ASSERT_LEVEL=3
FLAGS_C_HWPANELEMU += -DDEBUG=1
endif
FLAGS_C_HWPANELEMU += $(FLAGS_C_HWPANELEMU_CONFIG)

LINKER_FLAGS_HWPANELEMU := $(shell sdl2-config --libs)
ifeq ($(DEBUG), 1)
LINKER_FLAGS_HWPANELEMU += -mconsole # part of --libs, uncomment it if printf console is needed
endif
LINKER_FLAGS_HWPANELEMU += $(shell pkg-config $(LIBS_HWPANELEMU) --libs)

$(DIR_OBJ_HWPANELEMU):
	mkdir -p $@

$(DIR_OBJ_HWPANELEMU)/%.o: $(DIR_HWPANELEMU)/%.c | $(DIR_OBJ_HWPANELEMU)
	@echo "hwPanelEmulator C> $(notdir $<)"
	@$(CC) -c $(FLAGS_C_HWPANELEMU) $< -o $@

$(OBJECTS_HWPANELEMU): $(DIR_HWPANELEMU)/make.mk

-include $(wildcard $(DIR_OBJ_HWPANELEMU)/*.d)

# -include $(foreach odir, $(DIRS_OBJS_TARGET), $(wildcard $(odir)/*.d))
