#ifndef __PANEL_CONF_H
#define __PANEL_CONF_H

#define PANEL_NAME "SL seq"

#define PANEL_SCALE 2
#define PANEL_UNIT_SIZE 46
#define PAN_OFFSET 20
#define PAN_BUT_INTERVAL 4

#define PAN_BUT_INC ((PANEL_UNIT_SIZE + PAN_BUT_INTERVAL) * PANEL_SCALE)
#define PAN_ELEMENTS_WIDTH ((PANEL_UNIT_SIZE * 4 + PAN_BUT_INTERVAL * 3) * PANEL_SCALE)
#define PAN_1ST_ROW_INT ((PAN_ELEMENTS_WIDTH - (PANEL_UNIT_SIZE * PANEL_SCALE * 3)) / 4)

#define PANEL_SIZE_X (PAN_OFFSET * 2 / PANEL_SCALE + PANEL_UNIT_SIZE * 4 + PAN_BUT_INTERVAL * 3)
#define PANEL_SIZE_Y (PAN_OFFSET * 2 / PANEL_SCALE + PANEL_UNIT_SIZE * 4 + PAN_BUT_INTERVAL * 3 + (32 + 6) * 3 / 2)

// #define FORM_COLOR_R 125
// #define FORM_COLOR_G 127
// #define FORM_COLOR_B 108
// #define FORM_COLOR_A 0
// #define FORM_COLOR_LABEL 0xFF000000

// #define BUT_SIZE_Y 46 // must be same as x

#endif // __PANEL_CONF_H